### ISSUE TITLE
January 2015 Change Requests

### ISSUE THREAD

**Issue by davea** [mysociety/zurich_mobile#5]
This is an umbrella ticket for all changes required to the mobile app:

 * [x] mysociety/FixMyStreet-Commercial#664 - multiple photos per report
 * [x] mysociety/FixMyStreet-Commercial#665 - mandatory photos for specific categories
 * [x] mysociety/FixMyStreet-Commercial#667 - default map to satellite view
 * [x] mysociety/FixMyStreet-Commercial#668 - increase maximum zoom level
 * [x] mysociety/FixMyStreet-Commercial#670 - remove older pins from map

**Comment by osfameron** [comment]
Also some wordings changes *may* need tweaking in app:

 - [ ] https://github.com/mysociety/FixMyStreet-Commercial/issues/666 - photo hints and help text

**Comment by davea** [comment]
Yes, at the very least a new `'Use photos'` string was introduced in 84842a759d511e5495020801b342337db2bfc297.

Additionally `perllib/FixMyStreet/App/Controller/Photo.pm` in the main FMS repo has added `'Photo is required'` which is localised and passed through to the app.

**Comment by davea** [comment]
I have built an Android app ready for test. The file is `ZuriWieNeu.apk` inside `~davea/zurich` on firefly. It backs onto http://zurich.fixmystreet.staging.mysociety.org, not the live site.

Two known issues:

 - The old map imagery is being used, due to the tile alignment issue with the new tiles (see mysociety/FixMyStreet-Commercial#668)
 - The button to proceed to the next screen after adding more than one photo is in English due to a new string having been introduced and not yet translated.

I don't have an Android device to test this on, so can't guarantee it will work. Can someone give it a once-over?

**Comment by davea** [comment]
I've replaced that `.apk` with a newly built version of the app that includes the new map tiles and maximum zoom of 1:250.

**Comment by davea** [comment]
Feedback to be actioned:

 - [ ] Back button missing from pages including help page & disclaimer page
 - [ ] 'logged in as' field wraps and causes screen height issues on iPhone 4S
 - [ ] Previously selected photos remain on photo page after submitting report
 - [ ] Cursor is at incorrect position in email field
 - [ ] Street autocompletion list can't be scrolled
 - [ ] Check that reports are appearing in the admin interface from the mobile app
 - [ ] Differing fields based on category aren't implemented

**Comment by davea** [comment]
The app now forces **all** reports to have at least one photo attached. The user cannot proceed past the photo selection screen until a photo has been attached.

**Comment by davea** [comment]
This has been released on the app stores.
